version: "3.8"

services:
  # FastAPI App
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./orders.db
    volumes:
      - ./orders.db:/app/orders.db
    networks:
      - app_network

  # Celery Worker
  worker:
    build: .
    container_name: celery_worker
    command: ["celery", "-A", "app.services.celery", "worker", "--loglevel=info"]
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./orders.db
    volumes:
      - ./orders.db:/app/orders.db
    networks:
      - app_network

  # Redis
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

# Network configuration for containers to communicate
networks:
  app_network:
    driver: bridge